# Generated by Django 3.0.8 on 2020-12-04 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0004_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='por_programa',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cupon_Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.Cupon')),
                ('programa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.Programa')),
            ],
            options={
                'verbose_name': 'Cupón de programa',
                'verbose_name_plural': 'Cupones de programa',
            },
        ),
    ]
